### PR TITLE
Version 0.1

### PR DESCRIPTION
**Pull request by jasongaare**
This version adds the following:
- `possibleOutcomes` for elements
- `onClose` for elements
- `goToWalkthroughElementWithId` function
- `startWalkthroughAtElement` function
- `exitWalkthrough` function

### CODE REVIEW

**Comment by cormander** [comment]
Love this repo! I'm trying out this branch and am having an issue when I use the new `onClose()` tooltip prop, the function fires but the walk-through doesn't proceed to the next step. Any thoughts?

**Comment by jasongaare** [comment]
@cormander hello! Sorry for the delayed response. I've neglected getting this library up-to-date but I'm unsure why that is happening. It should do the following:

```
 onClose: () => {
  if (typeof currentElement.onClose === 'function') {
    currentElement.onClose();
  }
  goToNext();
},
```
where `goToNext` should move to the next step...

**Comment by jasongaare** [comment]
Do you have any other details? I'd love to get out a new version with some updates soon that I have locally

**Comment by cormander** [comment]
I'm not sure - haven't done much debugging as my use of it, for now, is exploratory in nature. I'll eventually circle back to this when I have a real need for it. May have something to do with the fact that I have layer upon layer of frameworks in my complex setup.

As far as updates go, please also see issue https://github.com/jasongaare/react-native-walkthrough/issues/5 where I have a workaround here: https://github.com/OurVoiceUSA/HelloVoter/blob/8a762feebf0b424412ab147f67dd23c92bd9e15e/mobile/patches/react-native-walkthrough-tooltip%2B1.0.2.patch

Feel free to close out this issue if you'd like, and I'll submit a patch or a PR in the future should I come back to it.

**Pull request merged**
