### PR TITLE
Add guide index to state to reuse WalkthroughElements

### PR DESCRIPTION
**Pull request by danielwinkler**

### CODE REVIEW

**Comment by gitstud** [comment]
This is great too, I think most apps that require walkthroughs have complex features that have multiple interactions (I.e. double tap + tap + long press on a single element).  Would love to see this go in, I'm down to review both open PR's if we can fix the conflicts @danielwinkler

**Comment by danielwinkler** [comment]
@gitstud First one is done!

**Comment by gitstud** [comment]
This looks good I approve!

**Comment by jasongaare** [comment]
@danielwinkler sorry for the delay - just pulled in the TypeScript PR... would you be able to resolve the conflicts with master so I can also merge this?

**Comment by danielwinkler** [comment]
Superseeded by #13  (due more work required by merge conflicts on this one)

**Comment by danielwinkler** [comment]
@gitstud i created a new , fresh PR and added an onFinish handler for the walkthrough
would be nice to get also your opinion on it!

**Pull request closed without merging**
